version: '3.9'

services:
  db:
    image: mysql:8.0
    volumes:
      - mysqldata:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: example
  api:
    build: .
    env_file:
      - .env
    restart: on-failure
    ports:
      - 8080:1323
    environment:
      DB_CONNECTION: root:example@tcp(db:3306)/gobook?charset=utf8mb4&parseTime=True&loc=Local
      JWT_SECRET: secret

volumes:
  mysqldata:
    external: true
