version: "3.9"

services:
  db:
    image: mysql:8.0
    volumes:
      - mysqldata:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: example

volumes:
  mysqldata:
    external: true
